import GppVerify.RiemannHypothesis.ArithmeticConformalKinematics
import Mathlib.Tactic

/-!
# Arithmetic logarithmic Hamiltonian flow

The principal-series character already identifies the spectral mode at positive scale
`a` with the real-time phase generated by the logarithmic energy `E(a)=log a`.
This file packages the resulting exact one-parameter unitary dynamics and its
OS/shadow reversal law.

No operator algebra, KMS existence theorem, or Riemann-hypothesis statement is asserted.
-/

namespace GppArithmeticTimeEvolution

open Complex
open GppArithmeticConformalKinematics

/-- Zero arithmetic time acts trivially. -/
@[simp] theorem arithmeticTimePhase_zero (a : ℝ) :
    arithmeticTimePhase 0 a = 1 := by
  simp [arithmeticTimePhase]

/-- Exact one-parameter group law generated by the logarithmic Hamiltonian. -/
theorem arithmeticTimePhase_add (tau sigma a : ℝ) :
    arithmeticTimePhase (tau + sigma) a =
      arithmeticTimePhase tau a * arithmeticTimePhase sigma a := by
  unfold arithmeticTimePhase
  rw [← Complex.exp_add]
  congr 1
  push_cast
  ring

/-- Every arithmetic real-time phase is unitary. -/
theorem arithmeticTimePhase_norm (tau a : ℝ) :
    ‖arithmeticTimePhase tau a‖ = 1 := by
  simp [arithmeticTimePhase]

/-- Time reversal gives the inverse phase. -/
theorem arithmeticTimePhase_neg_eq_inv (tau a : ℝ) :
    arithmeticTimePhase (-tau) a = (arithmeticTimePhase tau a)⁻¹ := by
  unfold arithmeticTimePhase
  rw [← Complex.exp_neg]
  congr 1
  push_cast
  ring

/-- On positive arithmetic scales, OS/shadow reversal of the principal-series
spectral momentum is exactly Hermitian conjugation of logarithmic time evolution. -/
theorem arithmeticTimePhase_neg_eq_star
    (tau a : ℝ) (ha : 0 < a) :
    arithmeticTimePhase (-tau) a =
      (starRingEnd ℂ) (arithmeticTimePhase tau a) := by
  rw [← principal_character_eq_arithmeticTimePhase (-tau) a ha,
    ← principal_character_eq_arithmeticTimePhase tau a ha]
  exact shadow_principal_logScaleCharacter_eq_conj tau (arithmeticEnergy a)

end GppArithmeticTimeEvolution

#print axioms GppArithmeticTimeEvolution.arithmeticTimePhase_add
#print axioms GppArithmeticTimeEvolution.arithmeticTimePhase_norm
#print axioms GppArithmeticTimeEvolution.arithmeticTimePhase_neg_eq_inv
#print axioms GppArithmeticTimeEvolution.arithmeticTimePhase_neg_eq_star
