import Mathlib.Tactic

/-!
# Finite Vandermonde energy

This module isolates the positivity half of the general finite-support
Cauchy--Binet formula for the two-parameter Fisher metric generated by the
sufficient statistics `X` and `X^2`.

For nonnegative weights, every ordered three-support contribution is a
nonnegative weight product times a squared Vandermonde.  Consequently the full
ordered triple energy is nonnegative for arbitrary finite support.  The separate
identity equating one sixth of this ordered energy with the covariance
determinant still requires the finite Cauchy--Binet/moment-Gram bridge.
-/

open scoped BigOperators

namespace GppFiniteVandermondeEnergy

/-- Ordered finite-support Vandermonde energy. Repeated indices contribute zero,
while every unordered triple with distinct indices occurs six times. -/
def orderedVandermondeEnergy {n : ℕ} (p x : Fin n → ℝ) : ℝ :=
  ∑ i : Fin n, ∑ j : Fin n, ∑ k : Fin n,
    p i * p j * p k *
      (((x i - x j) * (x i - x k) * (x j - x k)) ^ 2)

/-- Every weighted squared-Vandermonde contribution is nonnegative when the
three weights are nonnegative. -/
theorem weighted_vandermonde_sq_nonneg
    (pi pj pk xi xj xk : ℝ)
    (hpi : 0 ≤ pi) (hpj : 0 ≤ pj) (hpk : 0 ≤ pk) :
    0 ≤ pi * pj * pk * (((xi - xj) * (xi - xk) * (xj - xk)) ^ 2) := by
  positivity

/-- The ordered Vandermonde energy is nonnegative for every finite support with
nonnegative weights.  No normalization or distinctness assumption is needed. -/
theorem orderedVandermondeEnergy_nonneg
    {n : ℕ} (p x : Fin n → ℝ)
    (hp : ∀ i, 0 ≤ p i) :
    0 ≤ orderedVandermondeEnergy p x := by
  unfold orderedVandermondeEnergy
  apply Finset.sum_nonneg
  intro i hi
  apply Finset.sum_nonneg
  intro j hj
  apply Finset.sum_nonneg
  intro k hk
  exact weighted_vandermonde_sq_nonneg
    (p i) (p j) (p k) (x i) (x j) (x k) (hp i) (hp j) (hp k)

end GppFiniteVandermondeEnergy

#print axioms GppFiniteVandermondeEnergy.weighted_vandermonde_sq_nonneg
#print axioms GppFiniteVandermondeEnergy.orderedVandermondeEnergy_nonneg
