import Mathlib.Tactic

/-!
# Finite Vandermonde energy

This module isolates the positivity half of the general finite-support
Cauchy--Binet formula for the two-parameter Fisher metric generated by the
sufficient statistics `X` and `X^2`.

For nonnegative weights, every ordered three-support contribution is a
nonnegative weight product times a squared Vandermonde. Consequently the full
ordered triple energy is nonnegative for arbitrary finite support. A single
triple of positive weights at three distinct support points gives a strictly
positive contribution; this is the local witness needed for the strict Fisher
metric in the prime-gas application.
-/

open scoped BigOperators

namespace GppFiniteVandermondeEnergy

/-- Ordered finite-support Vandermonde energy. Repeated indices contribute zero,
while every unordered triple with distinct indices occurs six times. -/
def orderedVandermondeEnergy {n : ℕ} (p x : Fin n → ℝ) : ℝ :=
  ∑ i : Fin n, ∑ j : Fin n, ∑ k : Fin n,
    p i * p j * p k *
      (((x i - x j) * (x i - x k) * (x j - x k)) ^ 2)

/-- Every weighted squared-Vandermonde contribution is nonnegative when the
three weights are nonnegative. -/
theorem weighted_vandermonde_sq_nonneg
    (pi pj pk xi xj xk : ℝ)
    (hpi : 0 ≤ pi) (hpj : 0 ≤ pj) (hpk : 0 ≤ pk) :
    0 ≤ pi * pj * pk * (((xi - xj) * (xi - xk) * (xj - xk)) ^ 2) := by
  positivity

/-- A triple of strictly positive weights at three pairwise distinct support
points contributes strictly positive squared-Vandermonde energy. -/
theorem weighted_vandermonde_sq_pos
    (pi pj pk xi xj xk : ℝ)
    (hpi : 0 < pi) (hpj : 0 < pj) (hpk : 0 < pk)
    (hij : xi ≠ xj) (hik : xi ≠ xk) (hjk : xj ≠ xk) :
    0 < pi * pj * pk * (((xi - xj) * (xi - xk) * (xj - xk)) ^ 2) := by
  have h1 : xi - xj ≠ 0 := sub_ne_zero.mpr hij
  have h2 : xi - xk ≠ 0 := sub_ne_zero.mpr hik
  have h3 : xj - xk ≠ 0 := sub_ne_zero.mpr hjk
  have hv : (xi - xj) * (xi - xk) * (xj - xk) ≠ 0 :=
    mul_ne_zero (mul_ne_zero h1 h2) h3
  have hsq : 0 < ((xi - xj) * (xi - xk) * (xj - xk)) ^ 2 :=
    sq_pos_of_ne_zero hv
  positivity

/-- The ordered Vandermonde energy is nonnegative for every finite support with
nonnegative weights. No normalization or distinctness assumption is needed. -/
theorem orderedVandermondeEnergy_nonneg
    {n : ℕ} (p x : Fin n → ℝ)
    (hp : ∀ i, 0 ≤ p i) :
    0 ≤ orderedVandermondeEnergy p x := by
  unfold orderedVandermondeEnergy
  apply Finset.sum_nonneg
  intro i hi
  apply Finset.sum_nonneg
  intro j hj
  apply Finset.sum_nonneg
  intro k hk
  exact weighted_vandermonde_sq_nonneg
    (p i) (p j) (p k) (x i) (x j) (x k) (hp i) (hp j) (hp k)

end GppFiniteVandermondeEnergy

#print axioms GppFiniteVandermondeEnergy.weighted_vandermonde_sq_nonneg
#print axioms GppFiniteVandermondeEnergy.weighted_vandermonde_sq_pos
#print axioms GppFiniteVandermondeEnergy.orderedVandermondeEnergy_nonneg
