import GppVerify.RiemannHypothesis.FiniteVandermondeEnergy
import GppVerify.RiemannHypothesis.FiniteVandermondeExpansionKernel
import GppVerify.RiemannHypothesis.FiniteMomentFactorization
import GppVerify.RiemannHypothesis.FiniteFisherMomentBridge
import Mathlib.Tactic

/-!
# Arbitrary finite Fisher--Vandermonde identity

This module closes the finite-support algebraic bridge for the two-parameter
Fisher metric generated by `X` and `X^2`. The ordered squared-Vandermonde
energy is expanded pointwise and finite sums are distributed into raw moments.

The general-mass theorem below is deliberately division-free. This matters for
finite truncations of countable probability measures: their total mass need
not yet be one, even when the limiting measure is normalized.
-/

open scoped BigOperators

namespace GppFiniteFisherVandermondeIdentity

open GppFiniteVandermondeEnergy
open GppFiniteVandermondeExpansionKernel
open GppFiniteMomentFactorization
open GppFiniteFisherMomentBridge

/-- Weighted form of the squared three-point Vandermonde expansion.  Writing
all eighteen channels already in separable `(pᵢ xᵢ^a)(pⱼ xⱼ^b)(pₖ xₖ^c)`
form lets the finite triple sums be collapsed by
`triple_monomial_factorization` without commutative simp rearranging binders. -/
theorem weighted_vandermonde_sq_expansion
    (pi pj pk a b c : ℝ) :
    pi * pj * pk * (((a - b) * (a - c) * (b - c)) ^ 2) =
      (pi*a^4)*(pj*b^2)*(pk*c^0)
      - 2*(pi*a^4)*(pj*b^1)*(pk*c^1)
      + (pi*a^4)*(pj*b^0)*(pk*c^2)
      - 2*(pi*a^3)*(pj*b^3)*(pk*c^0)
      + 2*(pi*a^3)*(pj*b^2)*(pk*c^1)
      + 2*(pi*a^3)*(pj*b^1)*(pk*c^2)
      - 2*(pi*a^3)*(pj*b^0)*(pk*c^3)
      + (pi*a^2)*(pj*b^4)*(pk*c^0)
      + 2*(pi*a^2)*(pj*b^3)*(pk*c^1)
      - 6*(pi*a^2)*(pj*b^2)*(pk*c^2)
      + 2*(pi*a^2)*(pj*b^1)*(pk*c^3)
      + (pi*a^2)*(pj*b^0)*(pk*c^4)
      - 2*(pi*a^1)*(pj*b^4)*(pk*c^1)
      + 2*(pi*a^1)*(pj*b^3)*(pk*c^2)
      + 2*(pi*a^1)*(pj*b^2)*(pk*c^3)
      - 2*(pi*a^1)*(pj*b^1)*(pk*c^4)
      + (pi*a^0)*(pj*b^4)*(pk*c^2)
      - 2*(pi*a^0)*(pj*b^3)*(pk*c^3)
      + (pi*a^0)*(pj*b^2)*(pk*c^4) := by
  rw [vandermonde_sq_expansion]
  ring

/-- The ordered finite Vandermonde energy equals the cubic raw-moment
discriminant for arbitrary finite weighted support. No positivity or
normalization assumption is required. -/
theorem orderedVandermondeEnergy_eq_momentDiscriminant
    {n : ℕ} (p x : Fin n → ℝ) :
    orderedVandermondeEnergy p x =
      momentDiscriminant
        (rawMoment p x 0) (rawMoment p x 1) (rawMoment p x 2)
        (rawMoment p x 3) (rawMoment p x 4) := by
  unfold orderedVandermondeEnergy momentDiscriminant
  simp_rw [weighted_vandermonde_sq_expansion]
  simp only [Finset.sum_add_distrib, Finset.sum_sub_distrib,
    Finset.sum_mul, Finset.mul_sum]
  simp_rw [triple_monomial_factorization]
  ring

/-- The total mass `m₀ = rawMoment p x 0` is nonnegative whenever all weights
are nonnegative. -/
theorem rawMoment_zero_nonneg
    {n : ℕ} (p x : Fin n → ℝ)
    (hp : ∀ i, 0 ≤ p i) :
    0 ≤ rawMoment p x 0 := by
  unfold rawMoment
  simp only [pow_zero, mul_one]
  exact Finset.sum_nonneg fun i _ => hp i

/-- The total mass is strictly positive as soon as one finite-support weight is
strictly positive. -/
theorem rawMoment_zero_pos_of_witness
    {n : ℕ} (p x : Fin n → ℝ)
    (hp : ∀ i, 0 ≤ p i)
    (i : Fin n) (hpi : 0 < p i) :
    0 < rawMoment p x 0 := by
  unfold rawMoment
  simp only [pow_zero, mul_one]
  apply Finset.sum_pos'
  · intro a ha
    exact hp a
  · exact ⟨i, Finset.mem_univ i, hpi⟩

/-- General finite-support Fisher positivity without a normalization
assumption. For nonnegative weights, the division-free covariance determinant
numerator is nonnegative.

This is the correct finite theorem for raw truncations of a countable measure. -/
theorem fisherNumerator_nonneg
    {n : ℕ} (p x : Fin n → ℝ)
    (hp : ∀ i, 0 ≤ p i) :
    0 ≤ fisherNumerator
      (rawMoment p x 0) (rawMoment p x 1) (rawMoment p x 2)
      (rawMoment p x 3) (rawMoment p x 4) := by
  have hE : 0 ≤ orderedVandermondeEnergy p x :=
    orderedVandermondeEnergy_nonneg p x hp
  have hm0 : 0 ≤ rawMoment p x 0 := rawMoment_zero_nonneg p x hp
  have hbridge := six_fisherNumerator_eq_mass_mul_momentDiscriminant
    (rawMoment p x 0) (rawMoment p x 1) (rawMoment p x 2)
    (rawMoment p x 3) (rawMoment p x 4)
  rw [← orderedVandermondeEnergy_eq_momentDiscriminant p x] at hbridge
  nlinarith [mul_nonneg hm0 hE]

/-- **Strict finite-support Fisher positivity from one three-point witness.**
For nonnegative weights, one ordered triple with positive weights and three
pairwise distinct observable values makes the full mass-aware Fisher numerator
strictly positive. This is the finite-prefix persistence theorem needed for a
strict countable Fisher limit: once a prefix contains the witness, adding more
nonnegative states cannot destroy strictness of the Vandermonde energy. -/
theorem fisherNumerator_pos_of_witness
    {n : ℕ} (p x : Fin n → ℝ)
    (hp : ∀ a, 0 ≤ p a)
    (i j k : Fin n)
    (hpi : 0 < p i) (hpj : 0 < p j) (hpk : 0 < p k)
    (hij : x i ≠ x j) (hik : x i ≠ x k) (hjk : x j ≠ x k) :
    0 < fisherNumerator
      (rawMoment p x 0) (rawMoment p x 1) (rawMoment p x 2)
      (rawMoment p x 3) (rawMoment p x 4) := by
  have hm0 : 0 < rawMoment p x 0 :=
    rawMoment_zero_pos_of_witness p x hp i hpi
  have hE : 0 < orderedVandermondeEnergy p x :=
    orderedVandermondeEnergy_pos_of_witness p x hp i j k
      hpi hpj hpk hij hik hjk
  have hbridge := six_fisherNumerator_eq_mass_mul_momentDiscriminant
    (rawMoment p x 0) (rawMoment p x 1) (rawMoment p x 2)
    (rawMoment p x 3) (rawMoment p x 4)
  rw [← orderedVandermondeEnergy_eq_momentDiscriminant p x] at hbridge
  nlinarith [mul_pos hm0 hE]

/-- For normalized finite weights, the ordered Vandermonde energy is exactly
six times the Fisher covariance determinant. -/
theorem orderedVandermondeEnergy_eq_six_fisherDet
    {n : ℕ} (p x : Fin n → ℝ)
    (hnorm : rawMoment p x 0 = 1) :
    orderedVandermondeEnergy p x =
      6 * fisherDet (rawMoment p x 1) (rawMoment p x 2)
        (rawMoment p x 3) (rawMoment p x 4) := by
  rw [orderedVandermondeEnergy_eq_momentDiscriminant]
  rw [hnorm]
  exact momentDiscriminant_one_eq_six_fisherDet
    (rawMoment p x 1) (rawMoment p x 2) (rawMoment p x 3) (rawMoment p x 4)

end GppFiniteFisherVandermondeIdentity

#print axioms GppFiniteFisherVandermondeIdentity.weighted_vandermonde_sq_expansion
#print axioms GppFiniteFisherVandermondeIdentity.orderedVandermondeEnergy_eq_momentDiscriminant
#print axioms GppFiniteFisherVandermondeIdentity.rawMoment_zero_nonneg
#print axioms GppFiniteFisherVandermondeIdentity.rawMoment_zero_pos_of_witness
#print axioms GppFiniteFisherVandermondeIdentity.fisherNumerator_nonneg
#print axioms GppFiniteFisherVandermondeIdentity.fisherNumerator_pos_of_witness
#print axioms GppFiniteFisherVandermondeIdentity.orderedVandermondeEnergy_eq_six_fisherDet
