import Mathlib.Analysis.SpecialFunctions.Log.Deriv
import Mathlib.Tactic

/-!
# Primitive / double-prime logarithmic counterterm pairing

The smooth Möbius correction `-(1/2) li(sqrt x)` to the prime-counting density
contributes, after the critical half-density weight, a derivative proportional to
`-1 / (2 x log x)`.  Its antiderivative is therefore `-(1/2) log(log x)` on `x > 1`.

The exceptional `m = 2` prime-repetition channel carries the opposite logarithmic
counterterm `+(1/2) log(log x)`.  This file formalizes the elementary analytic core of
that pairing only.  It does not assume a prime number theorem remainder estimate and
makes no RH or global Weil-positivity claim.
-/

namespace GppPrimitiveSquareLogCounterterm

/-- The primitive-channel logarithmic counterterm generated by the first smooth
Möbius (`n = 2`) correction after the critical half-density weight. -/
def primitiveSquareLogCounterterm (x : ℝ) : ℝ :=
  -(1 / 2 : ℝ) * Real.log (Real.log x)

/-- The leading logarithmic counterterm of the `m = 2` repetition channel. -/
def doublePrimeLogCounterterm (x : ℝ) : ℝ :=
  (1 / 2 : ℝ) * Real.log (Real.log x)

/-- On `x > 1`, the derivative of `log(log x)` is exactly `1 / (x log x)`. -/
theorem hasDerivAt_log_log {x : ℝ} (hx : 1 < x) :
    HasDerivAt (fun y : ℝ => Real.log (Real.log y))
      (1 / (x * Real.log x)) x := by
  have hx0 : x ≠ 0 := by nlinarith
  have hlogpos : 0 < Real.log x := Real.log_pos hx
  have hlog0 : Real.log x ≠ 0 := ne_of_gt hlogpos
  have h := (Real.hasDerivAt_log hlog0).comp x (Real.hasDerivAt_log hx0)
  convert h using 1 <;> field_simp [hx0, hlog0] <;> ring

/-- The primitive-square counterterm differentiates to the negative logarithmic
singularity `-1/(2 x log x)`. -/
theorem hasDerivAt_primitiveSquareLogCounterterm {x : ℝ} (hx : 1 < x) :
    HasDerivAt primitiveSquareLogCounterterm
      (-(1 / 2 : ℝ) * (1 / (x * Real.log x))) x := by
  simpa [primitiveSquareLogCounterterm] using
    (hasDerivAt_log_log hx).const_mul (-(1 / 2 : ℝ))

/-- The `m = 2` counterterm has the opposite logarithmic derivative. -/
theorem hasDerivAt_doublePrimeLogCounterterm {x : ℝ} (hx : 1 < x) :
    HasDerivAt doublePrimeLogCounterterm
      ((1 / 2 : ℝ) * (1 / (x * Real.log x))) x := by
  simpa [doublePrimeLogCounterterm] using
    (hasDerivAt_log_log hx).const_mul (1 / 2 : ℝ)

/-- The two exceptional logarithmic counterterms cancel pointwise. -/
theorem primitive_double_counterterms_cancel (x : ℝ) :
    primitiveSquareLogCounterterm x + doublePrimeLogCounterterm x = 0 := by
  simp [primitiveSquareLogCounterterm, doublePrimeLogCounterterm]

end GppPrimitiveSquareLogCounterterm

#print axioms GppPrimitiveSquareLogCounterterm.hasDerivAt_log_log
#print axioms GppPrimitiveSquareLogCounterterm.hasDerivAt_primitiveSquareLogCounterterm
#print axioms GppPrimitiveSquareLogCounterterm.hasDerivAt_doublePrimeLogCounterterm
#print axioms GppPrimitiveSquareLogCounterterm.primitive_double_counterterms_cancel
