import GppVerify.RiemannHypothesis.PrimeFisherProbability
import GppVerify.RiemannHypothesis.PrimeHankelAllOrderStrict
import Mathlib.Tactic

/-!
# Strict centered two-observable prime-Fisher geometry

The probability-normalized prime-Fisher ensemble already has strictly positive
variance for `log n`.  Here we strengthen this to the full centered two-observable
score generated by `log n` and `(log n)^2`.

For every nonzero pair `(a,b)`, the centered score

  a (log n - E log n) + b ((log n)^2 - E (log n)^2)

has strictly positive normalized mean square.  This is the positive-definiteness
statement for the covariance/Fisher quadratic form, proved directly from the
all-order strict polynomial Gram theorem.  No determinant limit or finite
truncation is used.
-/

namespace GppPrimeFisherCenteredGeometry

open Polynomial
open GppPrimeFisherProbability
open GppPrimeHankelAllOrderStrict
open GppPrimeHankelFisherSpecialization

/-- First normalized logarithmic moment. -/
noncomputable def meanLog (beta : ℝ) : ℝ :=
  primeFisherExpectation beta (fun n : ℕ => Real.log n)

/-- Second normalized logarithmic moment. -/
noncomputable def meanLogSq (beta : ℝ) : ℝ :=
  primeFisherExpectation beta (fun n : ℕ => (Real.log n) ^ 2)

/-- Polynomial representing a centered linear combination of `x` and `x^2`. -/
def centeredScorePolynomial (beta a b : ℝ) : ℝ[X] :=
  C (-(a * meanLog beta + b * meanLogSq beta)) + C a * X + C b * X ^ 2

/-- Evaluation is exactly the centered score. -/
theorem centeredScorePolynomial_eval (beta a b x : ℝ) :
    (centeredScorePolynomial beta a b).eval x =
      a * (x - meanLog beta) + b * (x ^ 2 - meanLogSq beta) := by
  simp [centeredScorePolynomial]
  ring

/-- Centering only changes the constant coefficient, so a nonzero pair still gives
a nonzero polynomial. -/
theorem centeredScorePolynomial_ne_zero
    {beta a b : ℝ} (hab : a ≠ 0 ∨ b ≠ 0) :
    centeredScorePolynomial beta a b ≠ 0 := by
  intro hzero
  have h1 := congrArg (fun p : ℝ[X] => p.coeff 1) hzero
  have h2 := congrArg (fun p : ℝ[X] => p.coeff 2) hzero
  simp [centeredScorePolynomial] at h1 h2
  exact hab.elim (fun ha => ha h1) (fun hb => hb h2)

/-- **Strict centered prime-Fisher quadratic form.**  On `beta > 1`, every
nonzero linear combination of `log n` and `(log n)^2`, after subtracting its
expectation, has strictly positive probability-normalized mean square. -/
theorem normalized_centered_quadratic_pos
    {beta a b : ℝ} (hbeta : 1 < beta) (hab : a ≠ 0 ∨ b ≠ 0) :
    0 < ∑' n : ℕ, primeFisherProbability beta n *
      (a * (Real.log n - meanLog beta) +
        b * ((Real.log n) ^ 2 - meanLogSq beta)) ^ 2 := by
  let p : ℝ[X] := centeredScorePolynomial beta a b
  have hp : p ≠ 0 := centeredScorePolynomial_ne_zero hab
  have hnum : 0 < ∑' n : ℕ,
      fisherWeight beta n * (p.eval (Real.log n)) ^ 2 :=
    fisher_polynomial_tsum_pos_unconditional hbeta p hp
  have hmass : 0 < primeFisherMass beta := primeFisherMass_pos hbeta
  have heval : ∀ n : ℕ,
      p.eval (Real.log n) =
        a * (Real.log n - meanLog beta) +
          b * ((Real.log n) ^ 2 - meanLogSq beta) := by
    intro n
    exact centeredScorePolynomial_eval beta a b (Real.log n)
  have hrewrite :
      (∑' n : ℕ, primeFisherProbability beta n *
        (a * (Real.log n - meanLog beta) +
          b * ((Real.log n) ^ 2 - meanLogSq beta)) ^ 2) =
      (∑' n : ℕ, fisherWeight beta n * (p.eval (Real.log n)) ^ 2) /
        primeFisherMass beta := by
    rw [← tsum_div_const]
    apply tsum_congr
    intro n
    rw [heval n]
    unfold primeFisherProbability
    ring
  rw [hrewrite]
  exact div_pos hnum hmass

end GppPrimeFisherCenteredGeometry

#print axioms GppPrimeFisherCenteredGeometry.centeredScorePolynomial_ne_zero
#print axioms GppPrimeFisherCenteredGeometry.normalized_centered_quadratic_pos
