import GppVerify.CelestialHolography.ScalarBoxRegulatorBounds
import GppVerify.CelestialHolography.RegulatedBoxDilogSeries
import Mathlib.Tactic

/-!
# Uniform dilogarithm endpoint bound for the regulated scalar box

This file composes the exact regulator geometry bounds with the directly-defined
real dilogarithm power series.  It isolates a branch-free piece of the regulator
limit: the moving endpoint `x = η B` lies in `[0,12/31]`, hence both local
series values `Li₂(x)` and `Li₂(-x)` are uniformly bounded by `12/19`.

The Spence/inversion identities needed to move the original box dilogarithms
into these small arguments remain a separate analytic layer.
-/

namespace GppScalarBoxDilogEndpointBound

open GppScalarBoxRegulatorBounds GppRegulatedBoxDilogSeries

/-- Exact uniform bound for both small dilogarithm arguments generated by the
regulated box endpoint.  No branch identities are used here. -/
theorem etaB_li2_uniform_bound
    (η B : ℝ)
    (hη0 : 0 ≤ η) (hη : η ≤ 1 / 4)
    (hB0 : 0 ≤ B) (hB : B ≤ 48 / 31) :
    |li2Series (η * B)| ≤ 12 / 19 ∧
    |li2Series (-(η * B))| ≤ 12 / 19 := by
  rcases eta_mul_B_small η B hη0 hη hB0 hB with ⟨hx0, hxupper, hxhalf⟩
  have hx1 : η * B < 1 := by linarith
  have hden : 0 < 1 - η * B := by linarith
  have hfrac : η * B / (1 - η * B) ≤ 12 / 19 := by
    apply (div_le_iff₀ hden).2
    nlinarith
  constructor
  · exact (abs_li2Series_le_of_nonneg hx0 hx1).trans hfrac
  · exact (abs_li2Series_neg_le_of_nonneg hx0 hx1).trans hfrac

end GppScalarBoxDilogEndpointBound

#print axioms GppScalarBoxDilogEndpointBound.etaB_li2_uniform_bound
