import GppVerify.CelestialHolography.ScalarBoxLogSquareRemainder
import Mathlib.Analysis.SpecialFunctions.Log.NegMulLog
import Mathlib.Tactic

/-!
# Scalar-box regulator vanishing lemmas

The quantitative endpoint estimates reduce the remaining mass-regulator errors to
standard functions generated by `m * log m`.  Mathlib proves continuity of this
function at the origin, so the right-hand regulator limit follows without any
additional asymptotic axiom.
-/

namespace GppScalarBoxRegulatorVanishing

open Filter Set
open scoped Topology

/-- `m log m -> 0` from the physical side `m -> 0+`. -/
theorem tendsto_mul_log_nhdsGT_zero :
    Tendsto (fun m : ℝ => m * Real.log m) (𝓝[>] 0) (𝓝 0) := by
  have h : Tendsto (fun m : ℝ => m * Real.log m) (𝓝 0) (𝓝 0) := by
    simpa using Real.continuous_mul_log.continuousAt
  exact h.mono_left inf_le_left

/-- The absolute logarithmic regulator term also vanishes. -/
theorem tendsto_abs_mul_log_nhdsGT_zero :
    Tendsto (fun m : ℝ => |m * Real.log m|) (𝓝[>] 0) (𝓝 0) := by
  simpa using tendsto_mul_log_nhdsGT_zero.abs

/-- Squaring `m log m -> 0` gives the frequently occurring
`m^2 log^2 m -> 0` remainder in an algebraically stable form. -/
theorem tendsto_sq_mul_log_sq_nhdsGT_zero :
    Tendsto (fun m : ℝ => (m * Real.log m) ^ 2) (𝓝[>] 0) (𝓝 0) := by
  simpa using tendsto_mul_log_nhdsGT_zero.pow 2

end GppScalarBoxRegulatorVanishing

#print axioms GppScalarBoxRegulatorVanishing.tendsto_mul_log_nhdsGT_zero
#print axioms GppScalarBoxRegulatorVanishing.tendsto_abs_mul_log_nhdsGT_zero
#print axioms GppScalarBoxRegulatorVanishing.tendsto_sq_mul_log_sq_nhdsGT_zero
